# Generated by Django 2.1.3 on 2018-12-25 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dzrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
