# Generated by Django 2.1.3 on 2018-12-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dzrip', '0003_auto_20181227_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customermodel',
            table='Customer',
        ),
    ]
