# Generated by Django 2.1.3 on 2018-12-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20181227_2306'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('dzrip', '0004_auto_20181227_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='Customer',
        ),
    ]
