# Generated by Django 2.1.3 on 2019-01-12 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzrip', '0005_auto_20190112_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
